#Copyright MrSanZz
#Please don't recode this !.
"""-+')'-+''"">=-=-=-=!=!.<>:"?"{}|-=]''".""'>or=''"""

import marshal, base64
exec(marshal.loads(base64.b64decode("c2ACAABpbXBvcnQgbWFyc2hhbA0KaW1wb3J0IGJhc2U2NA0KZ2xvYmFsIHNhdmUNCmNsYXNzIHNhdmU6DQogICAgZGVmIHNhdmUoYXBpX2tleSk6DQogICAgICAgIGxvYyA9ICdhcGlfa2V5LnR4dCcNCiAgICAgICAgd2l0aCBvcGVuKGxvYywgJ3InKSBhcyBmaWxlOg0KICAgICAgICAgICAgbGluZXMgPSBmaWxlLnJlYWRsaW5lcygpDQoNCiAgICAgICAgbGluZXNbMF0gPSBzdHIoYXBpX2tleSkucmVwbGFjZSgiYiciLCAnJykucmVwbGFjZSgiJyIsICcnKSArICdccicNCg0KICAgICAgICB3aXRoIG9wZW4obG9jLCAndycpIGFzIGZpbGU6DQogICAgICAgICAgICBmaWxlLndyaXRlbGluZXMobGluZXMpDQpkZWYgZW5jcnlwdChkYXRhKToNCiAgICBlbmNyeXB0ZWRfZGF0YSA9IGJhc2U2NC5iNjRlbmNvZGUobWFyc2hhbC5kdW1wcyhkYXRhKSkNCiAgICByZXR1cm4gZW5jcnlwdGVkX2RhdGENCg0KdGV4dF90b19lbmNyeXB0ID0gaW5wdXQoIllvdXIgYXBpLWtleSA6ICIpLnJlcGxhY2UoJ3NrLScsICcnKQ0KZW5jcnlwdGVkX3RleHQgPSBlbmNyeXB0KHRleHRfdG9fZW5jcnlwdCkNCnJlc3VsdHMgPSBiJ2RldmF4LScrZW5jcnlwdGVkX3RleHQNCnNhdmUuc2F2ZShyZXN1bHRzKQ==")))